name: Build

on:
  push:
    branches: [ "master" ]
    paths:
    - .github/workflows/build.yml
    - CustomJSONData/**
    - CustomJSONData.sln

jobs:
  build:
    name: Build
    strategy:
      matrix:
        game-version: [ 1.29.1, 1.34.2, 1.37.1, 1.40.0 ]
    uses: Aeroluna/workflows/.github/workflows/bs-build-version-release.yml@master
    with:
      project-path: CustomJSONData/CustomJSONData.csproj
      game-version: ${{ matrix.game-version }}
    secrets: inherit

  create_release:
    name: Create Release
    needs: build
    permissions:
      contents: write
    uses: Aeroluna/workflows/.github/workflows/bs-create-release-from-date.yml@master
    with:
      project-path: CustomJSONData/CustomJSONData.csproj
    secrets: inherit
